### PR TITLE
Query `site.siteMetadata` so the title is populated

### PR DESCRIPTION
**Pull request by Putnam14**
This pull requests resolves Issue #37, `site.siteMetaData` is not being queried. The title could be changed, but 'Gatsby Contentful starter' is a good start.

### CODE REVIEW

**Comment by Putnam14** [comment]
Commit 1e89893 fixes an issue in this pull request, I was using destructuring assignment in my own code and forgot to change that.

**Comment by jpalmieri** [comment]
👏 
lgtm, except it's still `undefined` on the blog post template: https://github.com/Putnam14/gatsby-contentful-starter/blob/2d46621d35cb36c7739f89a817e84887d4d3a62c/src/templates/blog-post.js#L13

**Comment by jpalmieri** [comment]
Thanks, @Putnam14. Looks ok to you, @stefanjudis?

**Comment by Putnam14** [comment]
Glad I could help!

**Comment by nicgordon** [comment]
Great work, thanks team 👏

**Pull request merged**
