### PR TITLE
Gatsby v2 upgrade

### PR DESCRIPTION
**Pull request by jpalmieri**
I recently did this to my own project which was based on this starter, so here's some ❤️ back to the source.

I mostly just followed the [migration guide](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/). One thing to note is I traded `npm` for `yarn`, because I ran into [this issue](https://github.com/gatsbyjs/gatsby-starter-blog/issues/110).

### CODE REVIEW

**Comment by jpalmieri** [comment]
@stefanjudis I noticed this when I was deploying on netlify, and setting the YARN_VERSION to my local version (1.10.1) solved the issue. Would you be comfortable requiring users to use a yarn version above the failing version? If so, I can find the lowest working version. Also, if so, what would be the best way to require users to use above this version? I'm not sure of a way to specify this in the repo (e.g., a lockfile) other than simply specifying it as a dependency in the README. Do you?

Alternatively, if you have any ideas on how to resolve this in a different way, I'm open.

Also, greetings from JAMStackConf in San Francisco!

image

**Comment by ow** [comment]
This worked great for me too! I wanted to try and help contribute here but wasn't able to -- a change that needs to be made is that the `gatsby setup` script spits out `npm [x]` suggestions rather than yarn by default. I think it's in upstream but worth noting in the readme so it's less confusing!

**Comment by stefanjudis** [comment]
Hey Joe,

I hope you had a great time at JAMstack! I'm very sorry for the delay. :(

> Would you be comfortable requiring users to use a yarn version above the failing version?

I don't see an issue switching to yarn. Personally, I'm more in the npm camp but yeah... no strong opinions on my side. :)

> and setting the YARN_VERSION to my local version (1.10.1) solved the issue

I'm not sure I understand. :) I was running on exactly that version and ran into the issue.

## Update

I just updated yarn to 1.12.3 and everything runs well! 🎉 I'll have another quick look and request some changes (here and there npm pops still up). But then – happy to merge. :)

**Comment by jpalmieri** [comment]
@stefanjudis sorry for the silence! It's been a while since I had some time to work on this. I keep getting this error when trying to run `yarn run dev`. I haven't had time to figure it out, but I'll have time on Friday to look at it.

```
yarn dev
yarn run v1.12.3
$ gatsby develop
success open and validate gatsby-configs — 0.006 s
success load plugins — 0.105 s
error Plugin gatsby-transformer-sharp returned an error


  Error: The module '/Users/joep/workspace/gatsby-contentful-starter-1/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 59. This version of Node.js requires
  NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or `npm install`).

  - loader.js:718 Object.Module._extensions..node
    internal/modules/cjs/loader.js:718:18

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - v8-compile-cache.js:159 require
    [gatsby-contentful-starter-1]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - constructor.js:10 Object.<anonymous>
    [gatsby-contentful-starter-1]/[gatsby-plugin-sharp]/[sharp]/lib/constructor.js:10:15

  - v8-compile-cache.js:178 Module._compile
    [gatsby-contentful-starter-1]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10

  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32

  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12

  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3

  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17

  - v8-compile-cache.js:159 require
    [gatsby-contentful-starter-1]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - index.js:3 Object.<anonymous>
    [gatsby-contentful-starter-1]/[gatsby-plugin-sharp]/[sharp]/lib/index.js:3:15

  - v8-compile-cache.js:178 Module._compile
    [gatsby-contentful-starter-1]/[v8-compile-cache]/v8-compile-cache.js:178:30


error Cannot read property 'filter' of undefined


  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:287 Promise.mapSeries.catch.then.results
    [gatsby-contentful-starter-1]/[gatsby]/dist/utils/api-runner-node.js:287:42

  - util.js:16 tryCatcher
    [gatsby-contentful-starter-1]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'filter' of undefined

  - api-runner-node.js:287 Promise.mapSeries.catch.then.results
    [gatsby-contentful-starter-1]/[gatsby]/dist/utils/api-runner-node.js:287:42

  - util.js:16 tryCatcher
    [gatsby-contentful-starter-1]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [gatsby-contentful-starter-1]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [gatsby-contentful-starter-1]/[bluebird]/js/release/async.js:17:14


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by stefanjudis** [comment]
@jpalmieri That's very odd. I ran the whole installation and dev setup the last time and it works flawlessly. :/ Let me know if I can support somehow. :)

**Comment by jpalmieri** [comment]
@stefanjudis Actually, never mind about my last comment. Something must have been weird with my 
configuration. Thanks for offering your help.

I clone this branch in a new directory, ran the setup script, and `yarn run dev` worked fine.

I think I changed all of the npm's to yarn; if anything else is left to do, let me know. Otherwise, :shipit:

**Comment by stefanjudis** [comment]
@jpalmieri Alright! I did a final round – LGTM. 👍🏻 Let's merge this!

Thanks so much for contributing back! ❤️

clapping

**Pull request merged**
